name: dpp_app
description: Digital Diabetes Prevention Program - Skeleton App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.13.1
  local_auth: ^3.0.1
  font_awesome_flutter: ^11.0.0
  fl_chart: ^1.2.0
  firebase_core: ^4.10.0
  firebase_auth: ^6.5.3
  cloud_firestore: ^6.6.0
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  webview_flutter_platform_interface: any
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/ffq/beverages/
    - assets/images/ffq/cereals_breads_prep/
    - assets/images/ffq/condiments_sideitems/
    - assets/images/ffq/dairy_milk/
    - assets/images/ffq/fruits_seasonal_regular/
    - assets/images/ffq/meat_fish_eggs/
    - assets/images/ffq/pulses_legumes/
    - assets/images/ffq/snacks_sweets/
    - assets/images/ffq/vegetables/
